name: "Deploy to Test"

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - "sources/**"

jobs:
  deploy-test:
    name: "Deploy my cloud function"
    uses: abridgeai/github-templates/.github/workflows/cloud-function-deploy.yml@main
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    with:
      function-name: "my-function-name"
      runtime: "nodejs22"
      GCP_SA_EMAIL: ${{ vars.GCP_SA_EMAIL_OPERATIONS }}
      GCP_WORKLOAD_IDENTITY_PROVIDER: ${{ vars.GCP_WORKLOAD_IDENTITY_PROVIDER_OPERATIONS }}
