name: "Deploy to Test"

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  deploy-test:
    name: "Setup Gcloud"
    uses: abridgeai/github-templates/.github/workflows/setup-gcloud.yml@main
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    with:
      GCP_SA_EMAIL: ${{ vars.GCP_SA_EMAIL_OPERATIONS }}
      GCP_WORKLOAD_IDENTITY_PROVIDER: ${{ vars.GCP_WORKLOAD_IDENTITY_PROVIDER_OPERATIONS }}
    steps:
      # Add your gcloud commands here
      - name: Gcloud Info
        run: |
          gcloud info
      # Example: Running another gcloud command
      - name: List GCS Buckets
        run: |
          gcloud storage buckets list
