name: App Engine Deploy

on:
  workflow_call:
    inputs:
      app-yaml-path:
        required: true
        type: string
      GCP_SA_EMAIL:
        required: true
        type: string
      GCP_WORKLOAD_IDENTITY_PROVIDER:
        required: true
        type: string

jobs:
  deploy-appengine:
    name: "Deploy an app engine service"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3
      - id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          workload_identity_provider: ${{ inputs.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ inputs.GCP_SA_EMAIL }}
      - id: "deploy"
        uses: "google-github-actions/deploy-appengine@v2"
        with:
          deliverables: ${{ inputs.app-yaml-path }}
