name: Cloud Function Deploy

on:
  workflow_call:
    inputs:
      function-name:
        required: true
        type: string
      runtime:
        required: true
        type: string
      GCP_SA_EMAIL:
        required: true
        type: string
      GCP_WORKLOAD_IDENTITY_PROVIDER:
        required: true
        type: string

jobs:
  deploy-cloudfunction:
    name: "Deploy a cloud function"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3
      - id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          workload_identity_provider: ${{ inputs.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ inputs.GCP_SA_EMAIL }}
      - id: 'deploy'
        uses: 'google-github-actions/deploy-cloud-functions@v3'
        timeout-minutes: 10
        with:
          name: ${{ inputs.function-name }}
          runtime: ${{ inputs.runtime }}
